"""Public API for the local LeRobot dataset access layer."""

from .analysis import (
    DistributionSummary,
    EpisodeOverview,
    MotionEvent,
    VerifiedIssue,
    compute_episode_overview,
    detect_motion_events,
    run_full_analysis,
    summarize_distribution,
)
from .dataset import LeRobotDataset
from .errors import (
    DatasetAccessError,
    DatasetMetadataError,
    DatasetReferenceError,
    EpisodeNotFoundError,
    FieldNotFoundError,
    FrameNotFoundError,
    InvalidDatasetRootError,
    TimestampLookupError,
    TimestampOutOfRangeError,
    VideoNotFoundError,
    VideoReferenceError,
)
from .metrics import EpisodeMetrics, SyncDiagnostics, compute_episode_metrics
from .models import (
    DatasetMetadata,
    EpisodeMetadata,
    FeatureDeclaration,
    FeatureSchema,
    FrameRecord,
    TaskMetadata,
    TimeSeriesData,
    TimestampMatch,
    TimingInfo,
    VideoResource,
)
from .semantics import (
    ActionTargets,
    CameraPose,
    HandTracks,
    SemanticFrame,
    SemanticShapeError,
    parse_action_targets,
    parse_camera_pose,
    parse_frame_semantics,
    parse_hand_tracks,
)

__all__ = [
    "ActionTargets",
    "CameraPose",
    "DatasetAccessError",
    "DatasetMetadata",
    "DatasetMetadataError",
    "DatasetReferenceError",
    "DistributionSummary",
    "EpisodeMetadata",
    "EpisodeMetrics",
    "EpisodeNotFoundError",
    "EpisodeOverview",
    "FeatureDeclaration",
    "FeatureSchema",
    "FieldNotFoundError",
    "FrameNotFoundError",
    "FrameRecord",
    "HandTracks",
    "InvalidDatasetRootError",
    "LeRobotDataset",
    "MotionEvent",
    "SemanticFrame",
    "SemanticShapeError",
    "SyncDiagnostics",
    "TaskMetadata",
    "TimeSeriesData",
    "TimestampLookupError",
    "TimestampMatch",
    "TimestampOutOfRangeError",
    "TimingInfo",
    "VerifiedIssue",
    "VideoNotFoundError",
    "VideoReferenceError",
    "VideoResource",
    "compute_episode_metrics",
    "compute_episode_overview",
    "detect_motion_events",
    "parse_action_targets",
    "parse_camera_pose",
    "parse_frame_semantics",
    "parse_hand_tracks",
    "run_full_analysis",
    "summarize_distribution",
]
